Zadanie 1.

Powtórz przykład ze zbiorem Iris, ale podziel dane na treningowe i testowe (np. 80% i 20%). Wykorzystaj

from sklearn.model_selection import train_test_split

Naucz model i sprawdź jego skuteczność na zbiorze testowym przy pomocy funkcji/metod z sklearn.metrics

confusion_matrix
accuracy_score
classification_report

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier, export_text

In [2]:
iris = sns.load_dataset("iris")

In [3]:
X = iris.drop('species', axis=1)
y = iris['species']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [5]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [6]:
feature_names = X.columns.tolist()
text_representation = export_text(classifier, feature_names=feature_names)
print(text_representation)

|--- petal_width <= 0.80
|   |--- class: setosa
|--- petal_width >  0.80
|   |--- petal_width <= 1.65
|   |   |--- petal_length <= 4.95
|   |   |   |--- class: versicolor
|   |   |--- petal_length >  4.95
|   |   |   |--- sepal_length <= 6.05
|   |   |   |   |--- sepal_width <= 2.45
|   |   |   |   |   |--- class: virginica
|   |   |   |   |--- sepal_width >  2.45
|   |   |   |   |   |--- class: versicolor
|   |   |   |--- sepal_length >  6.05
|   |   |   |   |--- class: virginica
|   |--- petal_width >  1.65
|   |   |--- petal_length <= 4.85
|   |   |   |--- sepal_width <= 3.10
|   |   |   |   |--- class: virginica
|   |   |   |--- sepal_width >  3.10
|   |   |   |   |--- class: versicolor
|   |   |--- petal_length >  4.85
|   |   |   |--- class: virginica



In [7]:
y_pred = classifier.predict(X_test)

In [8]:
print(confusion_matrix(y_test, y_pred))
print('Accuracy: '+str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test, y_pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
Accuracy: 0.9666666666666667
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.92      0.96        13
   virginica       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



Zadanie 2.  Wczytaj do bazy (np. PythonML) dane z pliku weight.csv.

Prześlij dane kolumn Gender, Weight, Height do Pythona. Wylosuj z danych około 1000 osób. Podziel ten zbiór na dane treningowe i testowe. Z biblioteki sklearn.linear_model zaimportuj LogisticRegression. Naucz model na danych treningowych i sprawdź jego przewidywania dla danych testowych. Wypisz wyniki ewaluacji modelu tak jak w zadaniu 1.

In [9]:
PythonML = pd.read_excel('weight.xlsx')
PythonML.head()

Gender  Age  Weight  Height  Leg_Length  Arm_Length  Arm_circum  Waist
0       0  241    64.7     163        34.2        36.2        29.0   89.6
1       0  241    54.0     153        37.2        34.0        26.1   85.5
2       1  241    61.4     165        37.7        35.0        31.4   70.1
3       0  241    74.0     171        37.9        36.2        29.8   91.1
4       0  241    63.6     159        38.1        34.0        29.2   74.3

In [10]:
PythonML = PythonML[['Gender', 'Weight', 'Height']]
PythonML = PythonML.sample(n=1000, replace=False, random_state=1)
PythonML.head()

Gender  Weight  Height
3547       1    73.6     159
248        0    55.1     168
1653       0    56.3     166
2689       0    87.0     170
3128       1    86.7     179

In [11]:
X = PythonML.drop('Gender', axis=1)
y = PythonML['Gender']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [13]:
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression()
regression.fit(X_train, y_train)

LogisticRegression()

In [14]:
print('intercept:', regression.intercept_)
print('slope:', regression.coef_)

intercept: [-39.39794043]
slope: [[0.00652357 0.23195881]]


In [15]:
y_pred = regression.predict(X_test)

In [16]:
print(confusion_matrix(y_test, y_pred))
print('Accuracy: '+str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test, y_pred))

[[79 14]
 [15 92]]
Accuracy: 0.855
              precision    recall  f1-score   support

           0       0.84      0.85      0.84        93
           1       0.87      0.86      0.86       107

    accuracy                           0.85       200
   macro avg       0.85      0.85      0.85       200
weighted avg       0.86      0.85      0.86       200



Zadanie 3. 

Prześlij dane kolumn Gender, Weight, Height do Pythona. Wylosuj z danych około 1000 osób. Podziel ten zbiór na dane treningowe i testowe. Z biblioteki sklearn.neighbors zaimportuj KNeighborsClassifier. Naucz model na danych treningowych  dla k=1, 2,3 i 5 sąsiadów. Sprawdź przewidywania dla danych testowych dla poszczególnych k. Wypisz wyniki ewaluacji modelu tak jak w poprzednich zadaniach.

In [17]:
PythonML = pd.read_excel('weight.xlsx')
PythonML.head()

Gender  Age  Weight  Height  Leg_Length  Arm_Length  Arm_circum  Waist
0       0  241    64.7     163        34.2        36.2        29.0   89.6
1       0  241    54.0     153        37.2        34.0        26.1   85.5
2       1  241    61.4     165        37.7        35.0        31.4   70.1
3       0  241    74.0     171        37.9        36.2        29.8   91.1
4       0  241    63.6     159        38.1        34.0        29.2   74.3

In [18]:
PythonML = PythonML[['Gender', 'Weight', 'Height']]
PythonML = PythonML.sample(n=1000, replace=False, random_state=1)
PythonML.head()

Gender  Weight  Height
3547       1    73.6     159
248        0    55.1     168
1653       0    56.3     166
2689       0    87.0     170
3128       1    86.7     179

In [19]:
X = PythonML.drop('Gender', axis=1)
y = PythonML['Gender']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
def KNN_Classifier(X_train, y_train, X_test, y_test, k):
    neigh = KNeighborsClassifier(n_neighbors=k)
    neigh.fit(X_train, y_train)
    y_pred = neigh.predict(X_test)
    print('K = ', k)
    print(confusion_matrix(y_test, y_pred))
    print('Accuracy: '+str(accuracy_score(y_test, y_pred)))
    print(classification_report(y_test, y_pred))

In [22]:
KNN_Classifier(X_train, y_train, X_test, y_test, 1)

K =  1
[[78 15]
 [24 83]]
Accuracy: 0.805
              precision    recall  f1-score   support

           0       0.76      0.84      0.80        93
           1       0.85      0.78      0.81       107

    accuracy                           0.81       200
   macro avg       0.81      0.81      0.80       200
weighted avg       0.81      0.81      0.81       200



In [23]:
KNN_Classifier(X_train, y_train, X_test, y_test, 2)

K =  2
[[84  9]
 [37 70]]
Accuracy: 0.77
              precision    recall  f1-score   support

           0       0.69      0.90      0.79        93
           1       0.89      0.65      0.75       107

    accuracy                           0.77       200
   macro avg       0.79      0.78      0.77       200
weighted avg       0.80      0.77      0.77       200



In [24]:
KNN_Classifier(X_train, y_train, X_test, y_test, 3)

K =  3
[[75 18]
 [22 85]]
Accuracy: 0.8
              precision    recall  f1-score   support

           0       0.77      0.81      0.79        93
           1       0.83      0.79      0.81       107

    accuracy                           0.80       200
   macro avg       0.80      0.80      0.80       200
weighted avg       0.80      0.80      0.80       200



In [25]:
KNN_Classifier(X_train, y_train, X_test, y_test, 5)

K =  5
[[77 16]
 [16 91]]
Accuracy: 0.84
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        93
           1       0.85      0.85      0.85       107

    accuracy                           0.84       200
   macro avg       0.84      0.84      0.84       200
weighted avg       0.84      0.84      0.84       200

